#! /bin/sh

repo_dirs=(
$HOME/.dotfiles 
$HOME/.password-store 
$HOME/.local/bin 
$HOME/.todo
$HOME/.reminders
$HOME/Documents/notes
$HOME/.local/repos/make-total-deploy)

hr() { 
  i=1; while [ $i -le $COLUMNS ] ; do 
    i=$((i+1)); printf "%s" "${1:-=}"; 
  done; 
} # https://www.reddit.com/r/commandline/comments/sdy47y/print_a_horizontal_line_to_the_console_spanning/

print_origin() {
  printf "\e[32m$(git -C $1 config get remote.origin.url)\e[0m "
}

repo_pull ()
{
  for repo in ${repo_dirs[@]}
  do
    cd "$repo"
    print_origin
    git pull --rebase
    hr "-"
  done
}

repo_status ()
{
  for repo in ${repo_dirs[@]}
  do
    print_origin "$repo"
    git -C "$repo" status -u
    repo_not_pushed "$repo"
    hr "-"
  done
}

repo_not_pushed ()
{
  local unpushed=$(git -C $1 cherry -v)
  [ ! -z "$unpushed" ] && printf "\n\e[31mLocal unpushed commits:\e[36m\n$unpushed\e[0m\n"
}

case "$1" in
  "-p") repo_pull
  ;;
  *) repo_status
  ;;
esac

