#! /bin/sh

repo_dirs=(
$HOME/.dotfiles 
$HOME/.password-store 
$HOME/.local/bin 
$HOME/.todo
$HOME/.reminders
$HOME/Documents/notes
$HOME/.local/repos/make-total-deploy)
$HOME/.local/share/bmks)

hr() { 
  i=1; while [ $i -le $COLUMNS ] ; do 
    i=$((i+1)); printf "%s" "${1:-=}"; 
  done; 
} # https://www.reddit.com/r/commandline/comments/sdy47y/print_a_horizontal_line_to_the_console_spanning/

repo_print_origin() {
  printf "\e[32m$(git -C $1 config get remote.origin.url)\e[0m "
}

repo_not_pushed ()
{
  local unpushed=$(git -C $1 cherry -v)
  [ ! -z "$unpushed" ] && printf "\n\e[31mLocal unpushed commits:\e[36m\n$unpushed\e[0m\n"
}

repo_action()
{
  for repo in ${repo_dirs[@]}
  do
    repo_print_origin "$repo"
    git -C "$repo" $1
    hr "-"
  done
}

case "$1" in
  "-p") repo_action "pull --rebase" ;;
  "-P") repo_action "push" ;;
  *) repo_action "status -u" ;;
esac
