#!/usr/bin/bash

# Thanks Luke.
# https://github.com/LukeSmithxyz/mutt-wizard/blob/master/bin/mailsync
new=$(find\
		"$HOME/.local/share/mail/$1/"[Ii][Nn][Bb][Oo][Xx]/new/ \
		-type f 2> /dev/null)
	newcount=$(echo "$new" | sed '/^\s*$/d' | wc -l)
case 1 in
	$((newcount > 5)) )
  	echo "$newcount new mail for $1."
		notify-send "New Mail!" "󰶊  $newcount new mail(s) in \`$1\` account."
		;;
	$((newcount > 0)) )
		echo "$newcount new mail for $1."
		for file in $new; do
		  # Extract and decode subject and sender from mail.
			subject="$(sed -n "/^Subject:/ s|Subject: *|| p" "$file" |
				perl -CS -MEncode -ne 'print decode("MIME-Header", $_)')"
			from="$(sed -n "/^From:/ s|From: *|| p" "$file" |
				perl -CS -MEncode -ne 'print decode("MIME-Header", $_)')"
			from="${from% *}" ; from="${from%\"}" ; from="${from#\"}"
				notify-send "  $from:" "$subject"
		done
		;;
	*) echo "No new mail for $1." ;;
esac
