#! /bin/sh

DELIM="  "
BAT_ICONS=("" "" "" "" "")

CAP=$(cat /sys/class/power_supply/BAT0/capacity)
STAT=$(cat /sys/class/power_supply/BAT0/status)

if [ "$CAP" -le 10 ]; then
	printf "^c#f38ba8^${BAT_ICONS[0]}$DELIM^d^$CAP"
elif [ "$CAP" -le 25 ]; then
	printf "${BAT_ICONS[1]}$DELIM$CAP"
elif [ "$CAP" -le 50 ]; then
	printf "${BAT_ICONS[2]}$DELIM$CAP"
elif [ "$CAP" -le 75 ]; then
	printf "${BAT_ICONS[3]}$DELIM$CAP"
elif [ "$CAP" -le 100 ]; then
	printf "${BAT_ICONS[4]}$DELIM$CAP"
fi

if echo $STAT | grep -q "Charging"; then
	printf "^c#f9e2af^󱐋^d^"
fi
