#! /bin/sh
source colors

BAT_ICONS=("󰁺" "󰁺" "󰁻" "󰁻" "󰁼" "󰁽" "󰁿" "󰂀" "󰂁" "󰂂" "󰁹")
CAP=$(cat /sys/class/power_supply/BAT0/capacity)

printf "${BAT_ICONS[$(( ($CAP / 10) ))]} $CAP"

[[ $(grep "Charging" /sys/class/power_supply/BAT0/status) ]] && printf "^c$YELLOW^󱐋^d^"
