#!/bin/sh

source colors

case "$BLOCK_BUTTON" in
  1)  ;;
esac

if echo $(ps -A) | grep -q "picom"; then
  # printf "^b$CUSTOM_BG^^c$OVERLAY1^  󱣴 ^d^"
  printf "^c$OVERLAY1^󱣴 ^d^"
  killall picom
else
  # printf "^b$SURFACE0^  󱣴 ^d^"
  printf "󱣴 "
  picom -b
fi
