#!/bin/sh

source colors

MIC_ICONS=("^c$OVERLAY0^^c$TEXT^" "")
MIC_STAT=$(wpctl get-volume @DEFAULT_AUDIO_SOURCE@)

if echo $MIC_STAT | grep -q "MUTED"; then
	printf "${MIC_ICONS[0]}"
else
	printf "${MIC_ICONS[1]}"
fi
