#!/bin/sh

source colors

MIC_ICONS=("^c$SURFACE1^ ^c$TEXT^" "^c$TEXT^ ^c$TEXT^")
MIC_STAT=$(wpctl get-volume @DEFAULT_AUDIO_SOURCE@)
MIC_VAL=$(wpctl get-volume @DEFAULT_AUDIO_SOURCE@ | awk '{ print $2 * 100 }')

case "$BLOCK_BUTTON" in
  1)  wpctl set-mute @DEFAULT_SOURCE@ toggle ;;
esac

if echo $MIC_STAT | grep -q "MUTED"; then
	printf "${MIC_ICONS[0]}$MIC_VAL"
else
	printf "${MIC_ICONS[1]}$MIC_VAL"
fi
