#! /bin/sh
source colors

printf "^d^"

WIFI_ICONS=("󰤯 " "󰤟 " "󰤢 " "󰤥 " "󰤨 ")
WIFI_NETWORK=$(nmcli connection show | awk 'FNR == 2 { print $1 }')
SIG_STRENGTH=$(cat /proc/net/wireless | tr '.' ' ' | awk -F " " 'END{print $4}')

echo $(nmcli) | grep -q "wireguard" || echo $(nmcli) | grep -q "ovpn" && WIFI_ICONS=("󰤬 " "󰤡 " "󰤤 " "󰤧 " "󰤪 ")

show_wifi ()
{
  #  if [ "${SIG_STRENGTH}" -le -100 ]; then
  #   printf "${WIFI_ICONS[0]} $WIFI_NETWORK"
  # elif [ "${SIG_STRENGTH}" -le -80 ]; then
  #   printf "${WIFI_ICONS[1]} $WIFI_NETWORK"
  # elif [ "${SIG_STRENGTH}" -le -60 ]; then
  #   printf "${WIFI_ICONS[2]} $WIFI_NETWORK"
  # elif [ "${SIG_STRENGTH}" -le -40 ]; then
  #   printf "${WIFI_ICONS[3]} $WIFI_NETWORK"
  # elif [ "${SIG_STRENGTH}" -le -20 ]; then
  #   printf "${WIFI_ICONS[4]} $WIFI_NETWORK"
  # fi
   if [ "${SIG_STRENGTH}" -le -100 ]; then
    printf "${WIFI_ICONS[0]}"
  elif [ "${SIG_STRENGTH}" -le -80 ]; then
    printf "${WIFI_ICONS[1]}"
  elif [ "${SIG_STRENGTH}" -le -60 ]; then
    printf "${WIFI_ICONS[2]}"
  elif [ "${SIG_STRENGTH}" -le -40 ]; then
    printf "${WIFI_ICONS[3]}"
  elif [ "${SIG_STRENGTH}" -le -20 ]; then
    printf "${WIFI_ICONS[4]}"
  fi
}

case "$(nmcli connection show | awk 'FNR == 2 { print $(NF-1) }')" in
	"wifi") show_wifi ;;
	"ethernet") printf "󰈀" ;;
	*) printf "󱘖 "
esac
