#!/bin/sh
source colors

PLAYERCTL_ARTIST=$(playerctl metadata artist)
PLAYERCTL_TITLE=$(playerctl metadata title)
case "$(playerctl status)" in
  "Paused") printf "^b$SURFACE0^ ^c$GREEN^󰎈^c$TEXT^ $PLAYERCTL_ARTIST 󰇘 $PLAYERCTL_TITLE ^d^";;
  "Playing") printf "^b$SURFACE0^ ^c$GREEN^󰎈^c$TEXT^ $PLAYERCTL_ARTIST 󰇘 $PLAYERCTL_TITLE ^d^";;
esac
