#! /bin/sh
source colors

NUM_UPDATES=$(paru -Sy > /dev/null  && paru -Qu | wc -l)
PACKAGES=$(paru -Qu | awk '{print $1}')

case $BLOCK_BUTTON in
  1) notify-send "There are ${NUM_UPDATES} packages with available upgrades" "${PACKAGES}" ;;
esac

if [ ${NUM_UPDATES} -gt 0 ]; then
  printf "󰚰 ${NUM_UPDATES}^d^"
else
  exit
fi

