#! /bin/sh

WEATHER=$(curl --silent v2d.wttr.in/Lewisburg | grep "Weather:")

ICON=$(echo $WEATHER | awk -F " " '{print $2}')

TEMP=$(echo $WEATHER | tr ',' ' ' | awk -F " " '{print $5}')

printf "$ICON $TEMP"
