#! /bin/sh

NUM_UPDATES=$(paru -Sy > /dev/null  && paru -Qu | wc -l)
PACKAGES=$(paru -Qu | awk '{print $1}')

if [ ${NUM_UPDATES} -gt 0 ]; then
  printf "^c#fab387^󰚰 ^d^${NUM_UPDATES}"
  notify-send "There are ${NUM_UPDATES} packages with available upgrades" "${PACKAGES}"
else
  exit
fi
