#! /bin/sh

DELIM=" "
VOL_ICONS=("󰝟" "󰕿" "󰖀" "󰕾")
MIC_ICONS=("^c#6c7086^ ^d^" "^c#94e2d5^ ^d^")
VAL=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{ print $2 * 100 }')
STAT=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)
MIC_STAT=$(wpctl get-volume @DEFAULT_AUDIO_SOURCE@)

if echo $MIC_STAT | grep -q "MUTED"; then
	printf "${MIC_ICONS[0]}$DELIM"
else
	printf "${MIC_ICONS[1]}$DELIM"
fi

if echo $STAT | grep -q "MUTED"; then
	printf "${VOL_ICONS[0]}$DELIM$VAL"
elif [ $VAL -lt 33 ]; then
	printf "${VOL_ICONS[1]}$DELIM$VAL"
elif [ $VAL -le 66 ]; then
	printf "${VOL_ICONS[2]}$DELIM$VAL"
elif [ $VAL -le 100 ]; then
	printf "${VOL_ICONS[3]}$DELIM$VAL"
elif [ $VAL -gt 100 ]; then
	printf "${VOL_ICONS[3]}$DELIM^c#cba6f7^$VAL^d^"
fi
